### ISSUE TITLE
Plugin does not work with Gradle 2.12

### ISSUE THREAD

**Issue by pieces029** [groovy/groovy-android-gradle-plugin#107]
When the plugin gets applied to a build script that has been upgraded to gradle 2.12 the following error occurs

`A problem occurred evaluating root project 'test-app'.
> Failed to apply plugin [id 'groovyx.grooid.groovy-android']
   > Could not create an instance of type groovyx.grooid.internal.DefaultAndroidGroovySourceSet_Decorated.`

This can easily be reporduced by adding `'1.7' | '1.5.0'  | '2.12'` to the where clause in the FullCompilationSpec.

**Comment by dlew** [comment]
This is a common problem with most Gradle plugins because they changed the constructors for `DefaultSourceDirectorySet`.

[Their official answer is implement it yourself](https://discuss.gradle.org/t/defaultsourcedirectoryset-alternative/15193/5), but some plugins (cough) have just updated themselves to use the new constructor on 2.12 and above.
