### ISSUE TITLE
gradle plugin question:Could not find property 'assembleRelease' on root project

### ISSUE THREAD

**Issue by wustwg** [groovy/groovy-android-gradle-plugin#137]
Could not find property 'assembleCYOD' on root project.this question i have solved by use 'assembleRelease',it works on depedsOn:[].But when I set task order,using "'assembleRelease'.mustRunAfter(ndkBuild)",it doesn't work.
error :Error:(225, 0) No signature of method: java.lang.String.mustRunAfter() is applicable for argument types: (org.gradle.api.tasks.Exec_Decorated) values: [task ':ndkBuild'].
I know what it means and I search it by google,but there is nothing helpful, what should I do???thanks~~

**Comment by pieces029** [comment]
Hi wustwg,

It's hard to tell if this is an issue with the plugin or just a general question. If you could please provide more details and a failing sample that reproduces the issue you are seeing, then it can be investigated more. 

As this hasn't been provided, I would recommend posting this question to StackOverflow or the Gradle forms, because from the information that was provided appears to be a question about Gradle usage.
