### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by eldae** [groovy/groovy-android-gradle-plugin#140]
When I'm running tests for groovy-android-gradle-plugin only 6 of them tests are passing.

**Comment by AndrewReitz** [comment]
Care to provide more information, such as what command you used to run the tests, which tests are failing, and the output of those tests?

**Comment by eldae** [comment]
Sure,

When running tests from Android Studio only 6 tests are **passing**, namely:
* groovyx.GroovyAndroidExtensionSpec#should set options on groovy compile
* groovyx.GroovyAndroidPluginSpec#should apply groovy plugin on top of app plugin
* groovyx.GroovyAndroidPluginSpec#should apply groovy plugin on top of library plugin
* groovyx.GroovyAndroidPluginSpec#should add groovy extension
* groovyx.GroovyAndroidPluginSpec#should add groovy source sets

However, I came to realize that this result might not matter, because it may be the problem with the IDE and not with the tests. 

Running **gradlew test** or **gradlew fullTest** results in one failing test and this output: 


```
 groovyx.GroovyAndroidExtensionSpec > should add groovy source directories to groovy extension FAILED
     Expected no exception to be thrown, but got 'java.lang.IndexOutOfBoundsException'
         at spock.lang.Specification.noExceptionThrown(Specification.java:119)
         at groovyx.GroovyAndroidExtensionSpec.should add groovy source directories to groovy extension(GroovyAndroidExtensionSpec.groovy:88)

        Caused by:
        java.lang.IndexOutOfBoundsException: fromIndex = -2
            at java.util.SubList.<init>(AbstractList.java:620)
            at java.util.RandomAccessSubList.<init>(AbstractList.java:775)
            at java.util.AbstractList.subList(AbstractList.java:484)
            at groovyx.GroovyAndroidExtensionSpec.should add groovy source directories to groovy extension_closure3(GroovyAndroidExtensionSpec.groovy:85)
            at groovy.lang.Closure.call(Closure.java:426)
            at groovy.lang.Closure.call(Closure.java:442)
            at groovyx.GroovyAndroidExtensionSpec.should add groovy source directories to groovy extension(GroovyAndroidExtensionSpec.groovy:85)
                                                                                  
12 tests completed, 1 failed

**Comment by AndrewReitz** [comment]
Yeah, they must be run from the command line, IntelliJ/Android Studio doesn't understand all the setup.

As for the test failure, I'm not seeing this on the master branch, although there is a comment about what I did there specifically for getting around an issue on OSX. Since the tests also pass on Travis CI (linux), would you happen to be running on windows?

**Comment by eldae** [comment]
Yes, I run those tests on Windows. I tried again on OSX and they pass just fine. I guess it was a false alarm, thank you for your reply.

**Comment by AndrewReitz** [comment]
Would you be able to see the path at line 85 of GroovyAndroidExtensionSpec on Windows? 

It can be adjusted the test to work on all platforms, I just don't have a windows machine to be able to test and fit it with.

**Comment by eldae** [comment]
It fails because Windows is using backslashes instead of slashes. I've created the pull request with one solution to this problem: https://github.com/groovy/groovy-android-gradle-plugin/pull/141. Those workarounds are a bit hacky :)  It seems to me that there should be separate tests for every OS but I don't know if such setup is even possible.

**Comment by AndrewReitz** [comment]
I could make tests for each OS, but this issue is only arising because I have to do string manipulation and comparison to get the files to match what is expected. If I remember correctly there is an extra top level folder added that needs to be removed for the test to pass. The folder is added from TemporaryFolder and not because of the plugin, the plugin only cares about `'test/groovy/test', 'src/main/groovy'` existing, and since I'm doing string compares windows will have issues.

Thanks for the PR!
