### ISSUE TITLE
Incompatible with Eclipse Gradle STS

### ISSUE THREAD

**Issue by Banbury** [groovy/groovy-android-gradle-plugin#28]
The plugin doesn't provide the classpath and source sets for Eclipse Gradle STS.
Using 'Refresh All' doesn't add the source folders and the classpath containers to the Eclipse project.

**Comment by pieces029** [comment]
Android Studio is the official IDE for Android development, as well as the usage for this plugin. AS will correctly recognize the groovy source folders and gradle will correctly build the apk's. Using gradle will allow you to use any IDE or editor. For these reasons I will be closing this issue. If you have questions or feel that this issue was closed incorrectly please reopen and comment.
